function(add_unit_test testName)
    add_test(${testName} ${testName})
    add_executable(${testName} ${ARGN})
    target_link_libraries(${testName} PRIVATE test_library)
    # Link autodiff if available (header-only, requires Eigen3)
    if(TARGET autodiff2)
        target_link_libraries(${testName} PRIVATE autodiff2 Eigen3::Eigen)
    endif()
endfunction()